service: leads-to-slack
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    SLACK_WEBHOOK: ${ssm:SLACK_WEBHOOK}
    CAMPANY_LOGO: ${ssm:CAMPANY_LOGO}
    CAMPANY_WEBSITE: ${ssm:CAMPANY_WEBSITE}
functions:
  sendLead:
    handler: handler.sendLead
    events:
      - http:
          path: send-lead
          method: post
          cors: true
plugins:
  - serverless-plugin-typescript
