service: leads-to-slack
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    SLACK_WEBHOOK_URL: ${ssm:SLACK_WEBHOOK_URL}
    CAMPANY_LOGO_URL: ${ssm:CAMPANY_LOGO_URL}
    CAMPANY_WEBSITE_URL: Dreamcode.io  #${ssm:CAMPANY_WEBSITE_URL}
functions:
  sendLead:
    handler: handler.sendLead
    events:
      - http:
          path: send-lead
          method: post
          cors: true
plugins:
  - serverless-plugin-typescript
  - serverless-offline
